default: # see available parameters with command : app/console debug:container --parameters | grep sonata.admin
    sonata.admin.configuration.templates:
        default:
            user_block: SonataAdminBundle:Core:user_block.html.twig
        replace:
            user_block: SonataSyliusUserBundle:Admin/Block:user_block.html.twig
